<?php

/*
 * Fresns (https://fresns.org)
 * Copyright (C) 2021-Present Jarvis Tang
 * Released under the Apache-2.0 License.
 */

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StickersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('stickers')->delete();
        
        \DB::table('stickers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'default',
                'name' => 'default',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/smile.gif',
                'type' => 2,
                'parent_id' => NULL,
                'rank_num' => 1,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'coolmonkey',
                'name' => 'coolmonkey',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/01.gif',
                'type' => 2,
                'parent_id' => NULL,
                'rank_num' => 2,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'grapeman',
                'name' => 'grapeman',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/01.gif',
                'type' => 2,
                'parent_id' => NULL,
                'rank_num' => 3,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'face',
                'name' => 'Face',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/1.gif',
                'type' => 2,
                'parent_id' => NULL,
                'rank_num' => 4,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'smile',
                'name' => 'smile',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/smile.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 1,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'sad',
                'name' => 'sad',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/sad.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 2,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'biggrin',
                'name' => 'biggrin',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/biggrin.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 3,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'cry',
                'name' => 'cry',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/cry.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 4,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'huffy',
                'name' => 'huffy',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/huffy.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 5,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'shocked',
                'name' => 'shocked',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/shocked.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 6,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'tongue',
                'name' => 'tongue',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/tongue.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 7,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'shy',
                'name' => 'shy',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/shy.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 8,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'titter',
                'name' => 'titter',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/titter.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 9,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'sweat',
                'name' => 'sweat',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/sweat.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 10,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'mad',
                'name' => 'mad',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/mad.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 11,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'lol',
                'name' => 'lol',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/lol.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 12,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'loveliness',
                'name' => 'loveliness',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/loveliness.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 13,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'funk',
                'name' => 'funk',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/funk.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 14,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'curse',
                'name' => 'curse',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/curse.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 15,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'dizzy',
                'name' => 'dizzy',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/dizzy.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 16,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'shutup',
                'name' => 'shutup',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/shutup.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 17,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'sleepy',
                'name' => 'sleepy',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/sleepy.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 18,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'hug',
                'name' => 'hug',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/hug.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 19,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'victory',
                'name' => 'victory',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/victory.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 20,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'time',
                'name' => 'time',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/time.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 21,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'kiss',
                'name' => 'kiss',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/kiss.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 22,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 'handshake',
                'name' => 'handshake',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/handshake.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 23,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'call',
                'name' => 'call',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/default/call.gif',
                'type' => 1,
                'parent_id' => 1,
                'rank_num' => 24,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'code' => ':2_25:',
                'name' => ':2_25:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/01.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 1,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'code' => ':2_26:',
                'name' => ':2_26:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/02.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 2,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'code' => ':2_27:',
                'name' => ':2_27:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/03.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 3,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'code' => ':2_28:',
                'name' => ':2_28:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/04.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 4,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'code' => ':2_29:',
                'name' => ':2_29:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/05.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 5,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'code' => ':2_30:',
                'name' => ':2_30:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/06.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 6,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'code' => ':2_31:',
                'name' => ':2_31:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/07.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 7,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'code' => ':2_32:',
                'name' => ':2_32:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/08.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 8,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'code' => ':2_33:',
                'name' => ':2_33:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/09.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 9,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'code' => ':2_34:',
                'name' => ':2_34:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/10.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 10,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'code' => ':2_35:',
                'name' => ':2_35:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/11.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 11,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'code' => ':2_36:',
                'name' => ':2_36:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/12.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 12,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'code' => ':2_37:',
                'name' => ':2_37:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/13.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 13,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'code' => ':2_38:',
                'name' => ':2_38:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/14.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 14,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'code' => ':2_39:',
                'name' => ':2_39:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/15.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 15,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'code' => ':2_40:',
                'name' => ':2_40:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/coolmonkey/16.gif',
                'type' => 1,
                'parent_id' => 2,
                'rank_num' => 16,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'code' => ':3_41:',
                'name' => ':3_41:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/01.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 1,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'code' => ':3_42:',
                'name' => ':3_42:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/02.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 2,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'code' => ':3_43:',
                'name' => ':3_43:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/03.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 3,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'code' => ':3_44:',
                'name' => ':3_44:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/04.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 4,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'code' => ':3_45:',
                'name' => ':3_45:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/05.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 5,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'code' => ':3_46:',
                'name' => ':3_46:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/06.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 6,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'code' => ':3_47:',
                'name' => ':3_47:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/07.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 7,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'code' => ':3_48:',
                'name' => ':3_48:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/08.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 8,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'code' => ':3_49:',
                'name' => ':3_49:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/09.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 9,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'code' => ':3_50:',
                'name' => ':3_50:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/10.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 10,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'code' => ':3_51:',
                'name' => ':3_51:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/11.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 11,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'code' => ':3_52:',
                'name' => ':3_52:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/12.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 12,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'code' => ':3_53:',
                'name' => ':3_53:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/13.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 13,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'code' => ':3_54:',
                'name' => ':3_54:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/14.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 14,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'code' => ':3_55:',
                'name' => ':3_55:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/15.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 15,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'code' => ':3_56:',
                'name' => ':3_56:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/16.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 16,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'code' => ':3_57:',
                'name' => ':3_57:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/17.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 17,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'code' => ':3_58:',
                'name' => ':3_58:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/18.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 18,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'code' => ':3_59:',
                'name' => ':3_59:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/19.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 19,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'code' => ':3_60:',
                'name' => ':3_60:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/20.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 20,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'code' => ':3_61:',
                'name' => ':3_61:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/21.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 21,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'code' => ':3_62:',
                'name' => ':3_62:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/22.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 22,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'code' => ':3_63:',
                'name' => ':3_63:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/23.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 23,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'code' => ':3_64:',
                'name' => ':3_64:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/grapeman/24.gif',
                'type' => 1,
                'parent_id' => 3,
                'rank_num' => 24,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'code' => ':4_86:',
                'name' => ':4_86:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/1.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 1,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'code' => ':4_97:',
                'name' => ':4_97:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/2.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 2,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'code' => ':4_108:',
                'name' => ':4_108:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/3.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 3,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'code' => ':4_110:',
                'name' => ':4_110:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/4.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 4,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'code' => ':4_111:',
                'name' => ':4_111:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/5.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 5,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'code' => ':4_112:',
                'name' => ':4_112:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/6.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 6,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'code' => ':4_113:',
                'name' => ':4_113:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/7.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 7,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'code' => ':4_114:',
                'name' => ':4_114:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/8.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 8,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'code' => ':4_115:',
                'name' => ':4_115:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/9.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 9,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'code' => ':4_87:',
                'name' => ':4_87:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/10.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 10,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'code' => ':4_88:',
                'name' => ':4_88:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/11.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 11,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'code' => ':4_89:',
                'name' => ':4_89:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/12.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 12,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'code' => ':4_90:',
                'name' => ':4_90:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/13.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 13,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'code' => ':4_91:',
                'name' => ':4_91:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/14.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 14,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'code' => ':4_92:',
                'name' => ':4_92:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/15.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 15,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'code' => ':4_93:',
                'name' => ':4_93:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/16.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 16,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'code' => ':4_94:',
                'name' => ':4_94:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/17.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 17,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'code' => ':4_95:',
                'name' => ':4_95:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/18.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 18,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'code' => ':4_96:',
                'name' => ':4_96:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/19.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 19,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'code' => ':4_98:',
                'name' => ':4_98:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/20.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 20,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'code' => ':4_99:',
                'name' => ':4_99:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/21.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 21,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'code' => ':4_100:',
                'name' => ':4_100:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/22.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 22,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'code' => ':4_101:',
                'name' => ':4_101:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/23.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 23,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'code' => ':4_102:',
                'name' => ':4_102:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/24.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 24,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'code' => ':4_103:',
                'name' => ':4_103:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/25.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 25,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'code' => ':4_104:',
                'name' => ':4_104:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/26.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 26,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'code' => ':4_105:',
                'name' => ':4_105:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/27.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 27,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'code' => ':4_106:',
                'name' => ':4_106:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/28.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 28,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'code' => ':4_107:',
                'name' => ':4_107:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/29.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 29,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'code' => ':4_109:',
                'name' => ':4_109:',
                'image_file_id' => NULL,
                'image_file_url' => 'https://cdn.fresns.cn/smiley/face/30.gif',
                'type' => 1,
                'parent_id' => 4,
                'rank_num' => 30,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}